defmodule NotableWeb do
  @moduledoc """
  The entrypoint for defining your web interface, such
  as controllers, components, channels, and so on.

  This can be used in your application as:

      use NotableWeb, :controller
      use NotableWeb, :html

  The definitions below will be executed for every controller,
  component, etc, so keep them short and clean, focused
  on imports, uses and aliases.

  Do NOT define functions inside the quoted expressions
  below. Instead, define additional modules and import
  those modules here.
  """

  # Plug.Static serves only what is listed here, and the endpoint sets
  # `raise_on_missing_only` in dev - so every name below must exist on disk.
  # Brand raster assets are generated by `assets/brand/generate.sh`.
  def static_paths,
    do:
      ~w(assets fonts images robots.txt sitemap.xml llms.txt smb_stage_clear.wav) ++
        ~w(favicon.ico favicon.svg icon-mask.svg apple-touch-icon.png
           icon-192.png icon-512.png og-image.png site.webmanifest)

  def router do
    quote do
      use Phoenix.Router, helpers: false

      # Import common connection and controller functions to use in pipelines
      import Plug.Conn
      import Phoenix.Controller
      import Phoenix.LiveView.Router
    end
  end

  def channel do
    quote do
      use Phoenix.Channel
    end
  end

  def controller do
    quote do
      use Phoenix.Controller, formats: [:html, :json]

      import Plug.Conn

      unquote(verified_routes())
    end
  end

  def live_view do
    quote do
      use Phoenix.LiveView

      import Phoenix.LiveView, except: [put_flash: 3]
      import NotableWeb.Flash, only: [put_flash: 3]

      on_mount NotableWeb.Flash

      unquote(html_helpers())
    end
  end

  def live_component do
    quote do
      use Phoenix.LiveComponent

      unquote(html_helpers())
    end
  end

  def html do
    quote do
      use Phoenix.Component

      # Import convenience functions from controllers
      import Phoenix.Controller,
        only: [get_csrf_token: 0, view_module: 1, view_template: 1]

      # Include general helpers for rendering HTML
      unquote(html_helpers())
    end
  end

  defp html_helpers do
    quote do
      # HTML escaping functionality
      import Phoenix.HTML
      # Core UI components
      import NotableWeb.CoreComponents

      # Common modules used in templates
      alias NotableWeb.Layouts
      alias Phoenix.LiveView.JS

      # Routes generation with the ~p sigil
      unquote(verified_routes())
    end
  end

  def verified_routes do
    quote do
      use Phoenix.VerifiedRoutes,
        endpoint: NotableWeb.Endpoint,
        router: NotableWeb.Router,
        statics: NotableWeb.static_paths()
    end
  end

  @doc """
  When used, dispatch to the appropriate controller/live_view/etc.
  """
  defmacro __using__(which) when is_atom(which) do
    apply(__MODULE__, which, [])
  end
end
